---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : 'ruhoh/'

posts:
  permalink: /archive/:year/:month/:day/:filename
  summary_lines: 20
  latest: 10
  exclude: '~$'

pages:
  permalink: 'pretty'
  exclude: '~$'
