---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : neotwitter
production_url : 'http://idenizen.net/blog'
base_path : "/blog"

posts:
  permalink: /archive/:year/:month/:day/:filename/
  summary_lines: 20
  latest: 10
  exclude: '~$'

pages:
  permalink: 'pretty'
  exclude: '~$'

rss:
  latest: 20

#env: 'dev'
env: 'production'
