title : 互联网暂住客
tagline: 一只猫的宅家思想
author :
  name : H. Xu
  email : snakehsu@gmail.com
  github : celadevra
  twitter : celadevra
  feedburner : feedname

navigation :
  - archives/index.html
  - tags.html
  - categories.html
  - pages.html
  - about/index.markdown
  - changelog/index.md
  
